fix kubebuilder install location

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -35,7 +35,7 @@ jobs:
         run: |
           GO111MODULE=on go install github.com/onsi/ginkgo/ginkgo@v1.14.2
           if ! [[ -x $(go env GOPATH)/bin/golangci-lint ]]; then echo "golangci-lint not found; fetching"; curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.57.2; fi
-          if ! [[ -d ${{ github.workspace	}}/kubebuilder_2.3.1_linux_amd64 ]]; then echo "kubebuilder not found; fetching"; curl -sSfL https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_linux_amd64.tar.gz | tar zxvf -; fi
+          if ! [[ -d ${{ github.workspace	}}/kubebuilder_2.3.1_linux_amd64 ]]; then echo "kubebuilder not found; fetching"; curl -sSfL https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_linux_amd64.tar.gz | tar zxvf -; mkdir -p /home/runner/work/wave/wave/src/github.com/wave-k8s/wave/kubebuilder/1.29.0; mv kubebuilder_2.3.1_linux_amd64/bin /home/runner/work/wave/wave/src/github.com/wave-k8s/wave/kubebuilder/1.29.0; fi
           if ! [[ -x $(go env GOPATH)/bin/kustomize ]]; then echo "kustomize not found; fetching"; GO111MODULE=on go install sigs.k8s.io/kustomize/kustomize/v5@latest; fi
       - name: Download dependencies
         run: |
@@ -47,7 +47,7 @@ jobs:
         run: |
           export GOPATH=$(go env GOPATH)
           export PATH=$GOPATH/bin:$PATH
-          ./configure --with-kubebuilder=${{ github.workspace	}}/kubebuilder_2.3.1_linux_amd64/bin --with-kubectl=${{ github.workspace	}}/kubebuilder_2.3.1_linux_amd64/bin/kubectl
+          ./configure --with-kubebuilder=/home/runner/work/wave/wave/src/github.com/wave-k8s/wave/kubebuilder/1.29.0/bin  --with-kubectl=/home/runner/work/wave/wave/src/github.com/wave-k8s/wave/kubebuilder/1.29.0/bin/kubectl
         working-directory: ./src/github.com/${{ github.repository }}
       - name: Run Tests
         run: |
